# -*- coding: utf-8 -*-
"""expense_sharing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQQqcdizpCpIMNeWFUDJ8pOCvIth2T2b

# **Google Pay Expense Sharing Project**

# **Step 1: Setup**
"""

!pip install numpy prettytable

import numpy as np
import csv
from prettytable import PrettyTable
from datetime import datetime

friends = ["Alice", "Bob", "Carol", "David"]
expense_matrix = np.zeros((len(friends), len(friends)))  # Rows: Who paid, Columns: Who it's for
history_file = "expenses.csv"

# Initialize CSV file with headers
with open(history_file, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["DateTime", "Payer", "Beneficiaries", "Amount", "Description"])

"""# **Step 2: Adding Expenses**"""

def add_expense(payer, beneficiaries, amount, description="", custom_split=None):
    payer_idx = friends.index(payer)

    if custom_split:
        # Custom split
        for beneficiary, share in zip(beneficiaries, custom_split):
            beneficiary_idx = friends.index(beneficiary)
            expense_matrix[payer_idx][beneficiary_idx] += share
    else:
        # Equal split
        share_per_person = amount / len(beneficiaries)
        for beneficiary in beneficiaries:
            beneficiary_idx = friends.index(beneficiary)
            expense_matrix[payer_idx][beneficiary_idx] += share_per_person

    # Save transaction to CSV with timestamp
    with open(history_file, mode="a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            payer,
            ",".join(beneficiaries),
            amount,
            description
        ])

"""# **Step 3: Calculating Settlements**"""

def calculate_settlements():
    total_paid = np.sum(expense_matrix, axis=1)
    total_owed = np.sum(expense_matrix, axis=0)
    net_balance = total_paid - total_owed
    return net_balance

"""# **Step 4: Displaying Settlements**"""

def display_settlements():
    settlements = calculate_settlements()
    table = PrettyTable()
    table.field_names = ["Friend", "Settlement"]

    for i, friend in enumerate(friends):
        if settlements[i] > 0:
            table.add_row([friend, f"Should Receive ₹{settlements[i]:.2f}"])
        elif settlements[i] < 0:
            table.add_row([friend, f"Owes ₹{-settlements[i]:.2f}"])
        else:
            table.add_row([friend, "Is Settled"])

    print("Final Settlements:")
    print(table)

"""# **Step 5: Suggesting Payments**"""

def suggest_payments():
    settlements = calculate_settlements()
    creditors = [(friends[i], amt) for i, amt in enumerate(settlements) if amt > 0]
    debtors = [(friends[i], -amt) for i, amt in enumerate(settlements) if amt < 0]
    transactions = []

    while debtors and creditors:
        debtor, debt_amount = debtors.pop(0)
        creditor, credit_amount = creditors.pop(0)
        payment = min(debt_amount, credit_amount)
        transactions.append((debtor, creditor, payment))

        debt_amount -= payment
        credit_amount -= payment

        if debt_amount > 0:
            debtors.insert(0, (debtor, debt_amount))
        if credit_amount > 0:
            creditors.insert(0, (creditor, credit_amount))

    print("\nSuggested Transactions:")
    if transactions:
        for debtor, creditor, amount in transactions:
            print(f"{debtor} should pay ₹{amount:.2f} to {creditor}")
    else:
        print("No transactions needed. Everyone is settled.")

"""# **Step 6: Viewing Transaction History**"""

def show_history():
    print("\nTransaction History:")
    with open(history_file, mode="r") as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)

"""# **Step 7: Example and execution**"""

add_expense("Alice", ["Alice", "Bob", "Carol"], 1250, "Hotel bill")
add_expense("Bob", ["Bob", "Carol"], 800, "Taxi fare")
add_expense("Carol", ["Alice", "Bob", "Carol", "David"], 1785, "Dinner", custom_split=[500, 500, 500, 285])

display_settlements()
suggest_payments()
show_history()